config/routes.rb
Rails.application.routes.draw do
  mount_griddler
  get "/email_processor", to: proc { [200, {}, ["OK"]] }, as: "mandrill_head_test_request"

  resources :feeds, only: [:create, :show]

  root 'feeds#new'

end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :feed, inverse_of: :emails
end

app/models/entry.rb
class Entry
  include ActiveModel::Model
  attr_accessor :id, :created_at, :title, :body, :author

  def self.from_email email
    new(
      id: email.id,
      created_at: email.created_at,
      title: email.subject,
      body: if email.html.present? then email.html else email.text end,
      author: email.from,
    )
  end
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :emails, inverse_of: :feed, dependent: :destroy

  validates :title, presence: true
  validates :token, presence: true

  validates :token, uniqueness: true

  def initialize(*)
    super
    self.token ||= SecureRandom.hex 25
  end

  def to_param
    token
  end

  def entries
    emails.order(created_at: :desc).map { |email| Entry.from_email email }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter do
    @feed = Feed.new
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def new
  end

  def create
    @feed = Feed.new feed_params
    if ! @feed.save
      render :new
    end
  end

  def show
    @feed = Feed.find_by(token: params.fetch(:id))
    if @feed.present?
      render formats: :atom
    else
      @feed = Feed.new
      flash.now.alert = 'Feed not found! Create one right away on the form below.'
      render :new
    end
  end

  private

  def feed_params
    params.require(:feed).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/feeds/create.html.erb
<h2>The feed <em><%= @feed.title %></em> was created!</h2>

<dl>
  <dt>E-mail address</dt>
  <dd><%= "#{ @feed.token }@#{ request.host }" %></dd>

  <dt>RSS feed</dt>
  <dd><%= link_to feed_url(@feed, :rss), feed_url(@feed, :rss) %></dd>
</dl>

<p>
  All you have to do now is sign up for the newsletter with this e-mail address
  and add this RSS feed to your client. From now on, every e-mail received will
  become an entry on the RSS feed.
</p>

<p>
  Please, <strong>take note of those addresses, this is the last time they're
  going to be shown to you!</strong>
</p>

<p>
  <%= link_to 'Create another feed', root_path, class: 'btn btn-default' %>
</p>

app/views/feeds/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>Introduction</h2>

    <p>
      I love newsletters, but I hate receiving e-mails. Call me an oldie, but I
      still use RSS feeds to read my news and e-mails for communication. And I
      prefer to keep those two separate.
    </p>

    <p>
      Unfortunately, as newsletters have become popular, there are some great
      readings that are not available through RSS anymore. <strong>Kill the newsletter!</strong>
      exists to fill this gap.
    </p>

    <p>
      This service converts newsletters into RSS feeds.
    </p>

    <h2>How it works</h2>

    <ol>
      <li>
        Fill the form on the top of this page with a title which identifies the
        newsletter you want to transform into an RSS feed.
      </li>

      <li>You'll be given an e-mail address and a link to a RSS feed.</li>

      <li>Sign up for the newsletter with the e-mail address.</li>

      <li>Add the RSS feed to your client.</li>

      <li>
        From now on, every e-mail sent to that address becomes a new item on the RSS
        feed.
      </li>
    </ol>

    <h2>Caveats</h2>

    <h3>Subscription confirmation</h3>

    <p>
      Every newsletter sender worth its salt works hard to avoid becoming a source
      of spam. One of the first measures of protection is sending a subscription
      confirmation e-mail as the reader signs up. It contains a link that needs to
      be clicked to complete the registration.
    </p>

    <p>
      This service works just fine with confirmation e-mails. They show up as one
      entry on the feed, along with every other e-mail that arrives on the inbox
      given to you when you create the feed on the form above.
    </p>

    <p>
      In fact, it is one indirect benefit this service provides to you. You get to
      read the newsletters you like without having to disclose your e-mail
      address. Besides keeping your private information for yourself, it may help
      you keep under the radar of spammers.
    </p>

    <h3 id="link-to-post">Link to post</h3>

    <p>
      RSS entries usually link to the original article on the author's
      website. Unfortunately, there's no such equivalent on an e-mail, so the RSS
      entries for feeds generated using this service won't link to anything.
    </p>

    <p>
      That turns out to be less of a problem than it may seem. Usually newsletter
      authors try to mitigate issues in rendering on different e-mail clients by
      providing a link to a webpage with the same contents on top of every entry.
    </p>

    <p>
      If you don't want to read directly on your RSS client, you can follow such
      links.
    </p>

    <h3>Sharing RSS feeds</h3>

    <p>
      You may like this service and may want to share the RSS feed you created with
      other people. Or you may even be a newsletter author considering using this
      service to avoid the hassle of maintaining a RSS feed but still provide yet
      another way for your readers to access the content.
    </p>

    <p>
      <strong>Don't do it!</strong> Anyone with access to the e-mail address or RSS
      feed generated by this service may impersonate you! They could, for example,
      unsubscribe you from the newsletter or send you spam through your RSS feed.
    </p>

    <p>
      Think of the e-mail and RSS feed addresses given to you by this service as
      passwords or access tokens that you must keep private.
    </p>

    <p>
      If you like this service and want to share it with others, just point them to
      this webpage and let them create their own RSS feeds.
    </p>

    <p>
      I swear this is a real concern, not just a shameless way to self-promote :)
    </p>

    <h3>Privacy</h3>

    <p>
      I'll never share or sell the contents that come in this service inbox. But I
      do need to keep all the information on my servers, otherwise I couldn't
      provide the RSS feed to you.
    </p>

    <p>
      Therefore, the recommended use-case of this tool is to subscribe for public
      newsletters. I'd avoid using it for anything else, specially if it involves
      private data.
    </p>

    <h3>Unsubscription</h3>

    <p>
      No longer want to receive the newsletter you signed up for? Please, remember
      to unsubscribe from it before removing the RSS feed from your
      client, if possible. Almost every newsletter contains links for unsubscription
      on the footer so it shouldn't be hard to do.
    </p>

    <p>
      I'm running this service free for everyone, but I can't afford to spend lots
      of money on it. The less e-mails it receives, the smaller the stress on the
      servers and the easier it's going to be for me to keep them running.
    </p>

    <p>
      I'll never charge you and you only use what you need. Deal? ;)
    </p>

    <h3>Abuse</h3>

    <p>
      Handling other's people e-mail is hard. In fact, this is <a href="https://www.quora.com/How-can-I-convert-an-email-newsletter-to-an-RSS-feed?share=1">not the first service attempting to solve this very issue</a>. Before
      creating it, I searched all over the Internet for something equivalent and
      everyone seems to have gone out of business.
    </p>

    <p>
      I'm not pretty sure what's the reason that made them cease. But I can guess
      they were attacked by spammers or people tried to DoS them. Maybe by running
      this service I'll find out the reason they failed.
    </p>

    <p>
      If I find out that this service is being abused, I'll have to take it offline,
      which is worse for everyone, unfortunately. At least, this is free software
      and you'll always be able to
      <a href="#development">deploy it to your own servers</a>.
    </p>

    <h2 id="development">Development</h2>

    <p>
      This service runs on <a href="https://www.gnu.org/philosophy/free-sw.html">free software</a> licensed under the <a href="https://www.gnu.org/copyleft/gpl.html">GPL license</a>. The
      source code is available on <a href="https://github.com/leafac/kill-the-newsletter">GitHub</a>.
    </p>

    <h3>Contribute</h3>

    <p>
      Contributions are welcome, help make this service better! Feel free to open
      issues or pull requests on the repository at <a href="https://github.com/leafac/kill-the-newsletter">GitHub</a>.
    </p>

    <h3>Deploy your own</h3>

    <p>
      Either because you don't want to share your data with this service or because
      it may have ended up on some blacklist of a particularly nasty newsletter
      publisher, you're free to deploy your own installation to your servers.
    </p>

    <p>
      Instructions are available on the <a href="https://github.com/leafac/kill-the-newsletter#deployment">README for the project</a>.
    </p>

    <h3>Conclusion</h3>

    <p>
      I created this service to scratch my own itch, but I'll be glad if you find it
      useful too and maybe even share it with other people.
    </p>

    <p>
      If you want to get in touch, you can find me <a href="https://www.leafac.com">on my personal website</a>.
    </p>

    <p>Thanks for using <strong>Kill the newsletter!</strong></p>
  </div>
</div>

app/views/index/index.html.erb
<%= simple_form_for @feed  do |form| %>
  <%= form.input :title %>
  <%= form.button :submit %>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kill the newsletter!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <h1>Kill the newsletter!</h1>

    <p>Convert newsletters into RSS feeds.</p>

    <% if flash.alert %>
      <div class="alert alert-danger" role="alert"><%= flash.alert %></div>
    <% end %>

    <% unless @feed.persisted? %>
      <%= simple_form_for @feed do |form| %>
        <%= form.input :title %>
        <%= form.button :submit %>
      <% end %>
    <% end %>
  </header>

  <%= yield %>

</body>
</html>